# filepath: /home/parraes/winebrazil/src/yml/producao.yml
tags:
  - producao
consumes:
  - application/x-www-form-urlencoded
parameters:
  - name: produto
    in: query
    type: string
    required: false
    default: VINHO DE MESA, VINHO FINO DE MESA (VINIFERA), SUCO, DERIVADOS
    description: Produto a ser consultado
  - name: ano
    in: query
    type: integer
    required: false
    description: Ano da produção
responses:
  200:
    description: Consulta processada com sucesso
    schema:
      type: object
      properties:
        status:
          type: string